### ISSUE TITLE
Add-in not working in Microsoft Edge

### ISSUE THREAD

**Issue by Shepherd-rocks** [OfficeDev/Outlook-Add-in-ForwardEmail#3]
Hey,

it's currently not possible to start the Add-In in Microsoft Edge in an Office 365 Tenant with Exchange Online. Fired error is "SEC7111: HTTPS-Sicherheit beeinträchtigt durch data:font/truetype;base64" in dnserror.html (1,1).

Microsoft Edge 41.16299.371.0
Microsoft EdgeHTML 16.16299

The Add-In is working fine in Internet Explorer, Chrome & Firefox.

**Comment by JaoMarcos** [comment]
I also have the same problem

**Comment by lindalu-MSFT** [comment]
Hi, this repo isn't monitored. If you're still having issues, please go to https://github.com/OfficeDev/office-js/issues/new/choose.
